# Generated by Django 2.1.5 on 2019-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='download.png', upload_to='product_pics'),
        ),
    ]
