# Generated by Django 2.1.5 on 2019-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='Buyer', max_length=20, unique=True),
        ),
    ]
