# Generated by Django 2.1.1 on 2019-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='aadhar_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='bank_account_no',
            field=models.PositiveIntegerField(),
        ),
    ]
