# Generated by Django 2.1.1 on 2019-01-16 21:31

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190116_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Subcategory, null=True)),
                ('specification', models.CharField(max_length=100)),
            ],
        ),
    ]
